### ISSUE TITLE
Failed to use ReactiveTypedQueryImpl#getResultList

### ISSUE THREAD

**Issue by rj-hwang** [simter/simter-reactive-test#1]
```
Suppressed: org.hibernate.exception.GenericJDBCException: could not advance using next()
  at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
  ...
Caused by: org.postgresql.util.PSQLException: 这个 ResultSet 已经被关闭。
  at org.postgresql.jdbc.PgResultSet.checkClosed(PgResultSet.java:2741)
...
```

**Comment by rj-hwang** [comment]
Because result stream could not be use out of transaction:

```
public Flux<T> getResultList() {
  return wrapper.fromStream(() -> doInTransaction(TypedQuery::getResultStream));
}
```

forback to use getResultList: 

```
public Flux<T> getResultList() {
  return wrapper.fromIterable(() -> doInTransaction(TypedQuery::getResultList));
}
```
